[package]
name = "cola-crdt"
version = "0.1.0"
edition = "2021"
authors = ["Riccardo Mazzarini <me@noib3.dev>"]
license = "MIT"

[lib]
name = "cola"

[features]
serde = ["dep:serde"]

[dependencies.rand]
version = "0.8"

[dependencies.serde]
version = "1.0"
optional = true
