[package]
name = "cola"
version = "0.1.0"
edition = "2021"
authors = ["Riccardo Mazzarini <me@noib3.dev>"]
license = "MIT"

[features]
serde = ["dep:serde"]

[dependencies]
serde = { version = "1.0.163", optional = true }
uuid = { version = "1.3", features = ["v4"] }
